version: '3.7'

services:
  spark:
    build: 
      context: .
      dockerfile: spark.Dockerfile
    hostname: spark
    container_name: spark
    ports:
      - '18080:8080'
      - '7077:7077'
      - '4042:4042'
    # command: export AWS_ACCESS_KEY_ID=`aws configure get aws_access_key_id` && export AWS_SECRET_ACCESS_KEY=`aws configure get aws_secret_access_key` && export AWS_SESSION_TOKEN=`aws configure get aws_session_token` && tail -f /dev/null
    volumes:
      - ./:/spark_testing
      - ~/.aws:/root/.aws #aws cli config

