version: '3.7'

services:
  jenkins:
    build: 
      context: ./
      dockerfile: jenkins.Dockerfile
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./mnt:/var/jenkins_home/mnt
      #jenkins user
      - ~/.aws:/var/jenkins_home/.aws
      #root user
      - ~/.aws:/root/.aws